[programs.devnet]
oracle = "6Dgxvo5tMUAh1VXfHPg5oA75mJJi2jrxzbma7xtZFbAs"


[programs.localnet]
oracle = "78X8sVvG5FmDEQJWE5at6NS7VvUqQCZom66Vid4YMgE1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register tests/*.ts"

[workspace]
members = ["programs/oracle"]
