[package]
name = "oracle"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi =[]
default = []

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"


